version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres_db
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DATABASE}
      POSTGRES_HOST: ${DATABASE_HOST}
    restart: on-failure
